### ISSUE TITLE
Missing googleRegex on router.js 

### ISSUE THREAD

**Issue by ghost** [Kolobok12309/vue-router-webcache#17]
It's missing `const googleRegex = /^cache:[^:]+:(.+)/` on router.js after rendering this file. After I manual add this line, it's work perfectly
<img width="757" alt="image" src="https://user-images.githubusercontent.com/63275409/170163718-d3a3e8c6-bf48-497c-b043-11f88a51dd1e.png">

Please fix this issue for no more manual action in need

**Comment by Kolobok12309** [comment]
Big thanks for this issue, fix it in 1.1.6 version
