### ISSUE TITLE
Add compatibility with webpack 5

### ISSUE THREAD

**Issue by serphiy** [Kolobok12309/vue-router-webcache#8]
Webpack 5 uses `exports` field from package.json and all files not specified in `exports` (including `main` field) cause ModuleNotFound Error. See https://webpack.js.org/guides/package-exports
Please, add `".": "./dist/index.js"` to `exports`

**Comment by Kolobok12309** [comment]
@serphiy Thanks for this report, don't know about it. Add in next version
